# Generated by Django 4.2.4 on 2023-08-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_bill_payments_created_alter_bill_bill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
