# Generated by Django 4.2.4 on 2023-08-15 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_alter_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 15, 11, 59, 43, 766520, tzinfo=datetime.timezone.utc)),
        ),
    ]
