# Generated by Django 4.2.4 on 2023-08-15 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_alter_bill_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='bill_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payments_created',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_to_pay',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.AddField(
            model_name='bill',
            name='value_to_pay',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='value_to_pay',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
